### ISSUE TITLE
蓝叠5 Hyper-V扫描不到ADB

### ISSUE THREAD

**Issue by Weicoz** [MaaAssistantArknights/MAABH3#12]
提示如下
```
MAA BH3 CLI,
Github: https://github.com/MaaAssistantArknights/MAABH3

Usage: MAABH3_CLI.exe [adb_path] [adb_address] [task_name]...

Modify config.json to configure tasks.

Welcome to come and create a GUI for us! :)

MaaFramework Version: v1.1.0
MAABH3 Version: v0.4.5

Scanning for Devices...
No Devices Found
```

**Comment by dongwlin** [comment]
请上传debug目录下maa.log

**Comment by dongwlin** [comment]
@MistEO

**Comment by Weicoz** [comment]
[maa.log](https://github.com/MaaAssistantArknights/MAABH3/files/13179078/maa.log)

**Comment by Weicoz** [comment]
日志里面写着
scmd=["C:\\Program Files\\BlueStacks_nxt\\HD-Adb.exe","connect","127.0.0.1:5575"
unable to connect to 127.0.0.1:5575: cannot connect to 127.0.0.1:5575: 由于目标计算机积极拒绝，无法连接。 (10061)
但是我蓝叠5的ADB端口是55332

**Comment by Weicoz** [comment]
或者希望能有一个方法或者配置能直接配置ADB的IP与端口

**Comment by MistEO** [comment]
蓝叠的端口每次启动都不一样，要单独给他写个扫描的逻辑，还没做。你可以先手动改改 config.json 来配端口

**Comment by Weicoz** [comment]
config.json 要怎么改，有样板吗

**Comment by dongwlin** [comment]
我当时接入toolkit的时候改的太屎了，没考虑到这种情况，如果toolkit没扫到端口，就拿不到adb_config，所以config.json里配置端口也没用。不如试试把蓝叠的端口改成5555，这样toolkit可以扫描到。我晚点再改改cli的逻辑

**Comment by Weicoz** [comment]
hyper-v的蓝叠好像不支持自定义端口的，但是我电脑又要开hyper-v。。。

可以考虑读取蓝叠的配置文件里的端口去动态获取

**Comment by dongwlin** [comment]
现在可以手动输入设备信息了
