### ISSUE TITLE
是否可以考虑增加一个运行完成后关闭模拟器或者关闭bh3的选项

### ISSUE THREAD

**Issue by Elgalas** [MaaAssistantArknights/MAABH3#14]
目前maa设置的是运行完成后关闭模拟器，这样会导致运行脚本时直接模拟器就关闭了，BH3脚本无法正常运行。
设置为关闭明日方舟后，发现仍然会有问题，长时间无人值守的情况下，会因为没有关闭BH3，上方会提示“已在线XXX小时请注意休息“，会导致识别出错，目前观察一键减负页面会因这个提示框不能正常运行，而是退出当前页面并进入材料远程，不断循环。
最简单的解决方案大概就是增加一个运行完成后关闭模拟器或者关闭bh3的选项，应该就不会出现这个问题；或者是加一个出现提示框的时候先点掉提示框的逻辑。

**Comment by dongwlin** [comment]
在config里有关闭崩坏3的配置项
