### ISSUE TITLE
MUMU12 无法扫描到所需要执行自动化的模拟器

### ISSUE THREAD

**Issue by Georgebillion** [MaaAssistantArknights/MAABH3#16]
本人在下载0.5.0版本的MAABH3后执行CLI，在扫描设备的时候发现无法找到我所需要控制的模拟器，以下为CMD截图：
![image](https://github.com/MaaAssistantArknights/MAABH3/assets/40432824/a1243a8f-8f5a-4486-bf59-3f56f37dcccd)
下面这个图是MUMU12 ADB点开后的设备地址图，我需要控制的是16480，但MAA无法搜索到该设备，只弹出了其他2个我不需要控制的设备地址：
![image](https://github.com/MaaAssistantArknights/MAABH3/assets/40432824/10a24cf9-7136-4888-a2b5-1dcf407af6c1)
TODO：
需要解决MUMU12无法扫描到所控制的模拟器
RESULT：
解决以上问题并能开始运行自动化脚本
EXTRA：
附加几个图片说明：
1.
![image](https://github.com/MaaAssistantArknights/MAABH3/assets/40432824/f4e35a5d-b6de-4356-9317-ba8b7a456cab)
![image](https://github.com/MaaAssistantArknights/MAABH3/assets/40432824/70a50d99-e2f8-43ba-88a1-0056d81cd87f)
证明我在非中文文件夹内运行该程序并按照README说法进行操作
2.
![image](https://github.com/MaaAssistantArknights/MAABH3/assets/40432824/6e9faf14-fb88-4818-acc0-0760ca67417c)
证明模拟器已经打开并安装好了BH3
3.
![image](https://github.com/MaaAssistantArknights/MAABH3/assets/40432824/260374e5-ec60-4f9b-8f3f-18fa38d6bdfd)
证实所使用的模拟器为MUMU12
4.
![image](https://github.com/MaaAssistantArknights/MAABH3/assets/40432824/ad18dfb4-4d47-4e75-a6c8-c270121ac472)
![image](https://github.com/MaaAssistantArknights/MAABH3/assets/40432824/ffccc531-7cbf-4606-993e-27fc220f1f0c)
该设备内还运行着ALAS和SRC2个自动化脚本

**Comment by Georgebillion** [comment]
补充说明：已经手动修改过config.json文件内的ADB_SERVER字段，但无效，依旧会重新搜索

**Comment by dongwlin** [comment]
手动输入重新支持了，晚点会发个版，如果没扫到的话到时可以手动输入

**Comment by Georgebillion** [comment]
> 手动输入重新支持了，晚点会发个版，如果没扫到的话到时可以手动输入

大概要多久，另外提一嘴，如果多开是不是要类似于MAA的方法要多份文件？

**Comment by dongwlin** [comment]
@MistEO 玛丽，为啥mumu12的16480会扫不到捏？

**Comment by Georgebillion** [comment]
> @MistEO 玛丽，为啥mumu12的16480会扫不到捏？

需要我这边提供资料的话尽管说

**Comment by dongwlin** [comment]
> > 手动输入重新支持了，晚点会发个版，如果没扫到的话到时可以手动输入
> 
> 大概要多久，另外提一嘴，如果多开是不是要类似于MAA的方法要多份文件？

快的话大概今晚（？），目前多开的话确实要复制多份

**Comment by Georgebillion** [comment]
[maa.log](https://github.com/MaaAssistantArknights/MAABH3/files/13426876/maa.log)
