### ISSUE TITLE
适配启动其他渠道服

### ISSUE THREAD

**Issue by Oyuanchu** [MaaAssistantArknights/MAABH3#17]
我的是wegame端，要改那些源码，怎么找到这个版本的启动指令

**Comment by dongwlin** [comment]
![Snipaste_2023-11-28_18-47-25](https://github.com/MaaAssistantArknights/MAABH3/assets/97545700/649b5ad0-a0c9-4391-8378-4490ed176381)
wegame那边是全平台服吗？

**Comment by Oyuanchu** [comment]
是的

**Comment by dongwlin** [comment]
全平台服直接用官服的包就好了，里面可以选择服务器，切换成全平台服；如果你是想在桌面端直接使用，目前暂时是不可行的，借用速溶茶的话来说就是
![image](https://github.com/MaaAssistantArknights/MAABH3/assets/97545700/6dfb8dcb-0063-49b8-b6f8-a2f3d18624ae)

**Comment by dongwlin** [comment]
全平台服也算是官服，可以直接启动的

**Comment by Oyuanchu** [comment]
就是WeGame端登录全平台没找到登录器

**Comment by dongwlin** [comment]
> 就是WeGame端登录全平台没找到登录器

你是用模拟器吗

**Comment by Oyuanchu** [comment]
是雷电模拟器，我发现我这个桌面端meiy没有扫码登录
![{0A4BEACE-1E48-4c94-B741-7E0B7DF3E4E4}](https://github.com/MaaAssistantArknights/MAABH3/assets/69566610/0c4b5c5d-aee1-4228-86c7-8b4b5fd3fd02)

**Comment by dongwlin** [comment]
> 是雷电模拟器，我发现我这个桌面端meiy没有扫码登录 ![{0A4BEACE-1E48-4c94-B741-7E0B7DF3E4E4}](https://private-user-images.githubusercontent.com/69566610/286563372-0c4b5c5d-aee1-4228-86c7-8b4b5fd3fd02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTUzNDEsIm5iZiI6MTcwMTI1NTA0MSwicGF0aCI6Ii82OTU2NjYxMC8yODY1NjMzNzItMGM0YjVjNWQtYWVlMS00MjI4LTg2YzctOGI0YjVmZDNmZDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEwNTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NTA3MWYwZjk4Yjc5MWEwNGNkZjRlYTBhMTEzYmFlOTEyMDU5Y2RlM2ZmNjI2ZGFhZThiNDM1ZjQ0MDVkOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tAsuBptkNUkc3w9kBPCL_yAAbI1TX8DDJMuuyH4DJeI)

不用扫码登陆啊，直接进去就好了
