### ISSUE TITLE
蓝叠5 adb连接失败

### ISSUE THREAD

**Issue by Loshepherd** [MaaAssistantArknights/MAABH3#20]
[maa.log](https://github.com/MaaXYZ/MAABH3/files/15024807/maa.log)
![image](https://github.com/MaaXYZ/MAABH3/assets/89327296/0abed56d-7d14-4195-86c9-11b767a86f81)
启动MAABH3_CLI.exe时报错，错误信息与日志如上。

**Comment by Loshepherd** [comment]
[maa.log](https://github.com/MaaXYZ/MAABH3/files/15024851/maa.log)

**Comment by Loshepherd** [comment]
[default.json](https://github.com/MaaXYZ/MAABH3/files/15024859/default.json)
我的adb配置如上。我不是很理解"device_name"字段，请问在蓝叠5国际版中，它应当如何填写？

**Comment by Loshepherd** [comment]
![image](https://github.com/MaaXYZ/MAABH3/assets/89327296/e6031f7e-39bb-4119-8af6-2487f15c1ff0)
蓝叠5的adb调试已开启

**Comment by dongwlin** [comment]
> [default.json](https://github.com/MaaXYZ/MAABH3/files/15024859/default.json) 我的adb配置如上。我不是很理解"device_name"字段，请问在蓝叠5国际版中，它应当如何填写？

这个可以随便填写，可以理解为一个模拟器的备注，默认是模拟器的名称；拿mumu12模拟器举例：MuMuPlayer12

**Comment by dongwlin** [comment]
你试试把 `./config/control/default.json` 里 `touch` 的值改成 `1` 试试

**Comment by Loshepherd** [comment]
非常感谢，问题解决了

**Comment by dongwlin** [comment]
但 `touch` 为 `1` 时是直接使用adb来进行模拟操作，万象虚境可能会有些连招无法使用 ~~,如果强度够的话不用那些连招也没啥关系~~ ；你也可以尝试将 `touch` 设置为 `2` 时是否可用
