### ISSUE TITLE
舰团委托回收任务在提交时失败

### ISSUE THREAD

**Issue by Sorarua** [MaaAssistantArknights/MAABH3#21]
![image](https://github.com/MaaXYZ/MAABH3/assets/43319035/05e8f526-bcb6-4f78-a00d-e790b2e36e72)
不能识别并点击提交按钮，卡在这个页面
![image](https://github.com/MaaXYZ/MAABH3/assets/43319035/f1483a43-ff36-4915-aa17-13d8ffe57e3d)

同样会卡住的还有每日领取奖励，不能识别任务按钮，会一直停在舰桥页面，只有我手动按了任务后，才能继续执行

**Comment by dongwlin** [comment]
上传log看看，在debug目录下

**Comment by Sorarua** [comment]
[maa.log](https://github.com/user-attachments/files/15520976/maa.log)

**Comment by dongwlin** [comment]
任务导航修了 bedbf5e1360ff1be64ceba43ed179dd778d09e93
