### ISSUE TITLE
有没有QQ群

### ISSUE THREAD

**Issue by qincenhua** [MaaAssistantArknights/MAABH3#23]
想进QQ群有些问题不会怎么没有应用程序呀exe安装包这种

**Comment by dongwlin** [comment]
README里有

**Comment by qincenhua** [comment]
windows11系统 主要安装是哪个包 我还是喜欢一个安装包exe双击运行然后在桌面创建快捷方式在双击运行应用程序就可以启动
后续考虑做一下不cmd让人看的一头雾水

**Comment by qincenhua** [comment]
![Screenshot_20241020_170442](https://github.com/user-attachments/assets/8eceddac-50c8-462a-a5fe-5ba9a58c7cc4)
这么多个解压包我也不知道哪个是对应的一个个下载全是CMD窗口
可以告知一下QQ群号多少不?
希望能后续优化一下就是一个安装程序为exe然后到桌面双击运行勾选对应的功能就能直接使用 Download .NET Framework 4.8.1 有些人没有安装这个会安装失败希望也能一并自动解压安装完成

**Comment by qincenhua** [comment]
![Uploading Screenshot_20241020_170442.jpg…]()

**Comment by qincenhua** [comment]
![Screenshot_20241020_170442](https://github.com/user-attachments/assets/cfe40eaf-5a8a-43ed-993b-d73cc5f34dee)

**Comment by dongwlin** [comment]
> README里有

👆去看README
