### ISSUE TITLE
homeland会持续停留在“所需关卡次数不足”

### ISSUE THREAD

**Issue by JeffWu97** [MaaAssistantArknights/MAABH3#3]
执行环境：mumu12，win10

![屏幕截图 2023-09-09 200506](https://github.com/MaaAssistantArknights/MAABH3/assets/32473560/b8775d22-3032-4a7e-a623-b6766918f98d)

**Comment by dongwlin** [comment]
ok，我这边看看

**Comment by dongwlin** [comment]
可以上传这个界面点“返回”后的截图吗，我需要看看

**Comment by JeffWu97** [comment]
> 可以上传这个界面点“返回”后的截图吗，我需要看看

![屏幕截图 2023-09-09 204820](https://github.com/MaaAssistantArknights/MAABH3/assets/32473560/6b508106-0180-4471-9669-3d3aa4a076f4)

**Comment by dongwlin** [comment]
理解了

**Comment by dongwlin** [comment]
f8592417bce81a6cc17b158bd65a2e928066c7ce fixed
