### ISSUE TITLE
作者有考虑出一个工具的使用教程吗？不知道本工具该如何使用。

### ISSUE THREAD

**Issue by ZlatanCN** [MaaAssistantArknights/MAABH3#4]

**Comment by dongwlin** [comment]
晚点会考虑，现在你是哪里不会用？

**Comment by BalconyJH** [comment]
能不能教教build(

**Comment by dongwlin** [comment]
> 能不能教教build(

README里有build的说明

**Comment by BalconyJH** [comment]
> > 能不能教教build(
> 
> README里有build的说明

沒事了剛build出來了

**Comment by ZlatanCN** [comment]
> 晚点会考虑，现在你是哪里不会用？

下载完点开exe，弹出cmd，不太清楚接下来的步骤

**Comment by JeffWu97** [comment]
> > 晚点会考虑，现在你是哪里不会用？
> 
> 下载完点开exe，弹出cmd，不太清楚接下来的步骤

1. 输入使用模拟器的adb绝对路径，一般在模拟器安装目录里面。供参考：mumu12叫adb.exe，bluestack是HD-Adb.exe，其余模拟器需要自行查询
2. 输入连接模拟器的连接地址+端口号，同样自行查询，[可参考MAA的文档](https://maa.plus/docs/1.1-%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%9E%E6%8E%A5)。每个模拟器都有默认的端口号。mumu12默认16384。多开会导致分配不同的端口，要另行查看。开启hyper-v会导致端口不断变动，这块详细可参考MAA的[QA](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v)
3. 输入要执行的任务，用空格来间隔

**Comment by JeffWu97** [comment]
> 晚点会考虑，现在你是哪里不会用？

能不能教教怎么读会更快入手？看得一头雾水，太久没接触编程和CPP，同时也比较菜。MaaFramwork那边又只有一个pipeline doc。想参与开发和弄一个无期迷途的但不会orz

目前是下了个vs2022加断点main.cpp慢慢去看orz，有点难度。是不是从commit record那边从init开始慢慢看上去会比较好入手？

**Comment by dongwlin** [comment]
> > 晚点会考虑，现在你是哪里不会用？
> 
> 下载完点开exe，弹出cmd，不太清楚接下来的步骤

1. 打开之后要等待它扫描设备
2. 扫描完成后，选择要连接的设备，如果是第一次打开会让你选择执行的任务和客户端
3. 选择客户端
4. 输入要执行的任务，用空格来间隔

只有第一次或者没有config的情况下会让你选择执行的任务和客户端，你也根据自己的需求更改config

**Comment by dongwlin** [comment]
> > > 晚点会考虑，现在你是哪里不会用？
> > 
> > 
> > 下载完点开exe，弹出cmd，不太清楚接下来的步骤
> 
> 1. 输入使用模拟器的adb绝对路径，一般在模拟器安装目录里面。供参考：mumu12叫adb.exe，bluestack是HD-Adb.exe，其余模拟器需要自行查询
> 2. 输入连接模拟器的连接地址+端口号，同样自行查询，[可参考MAA的文档](https://maa.plus/docs/1.1-%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%9E%E6%8E%A5)。每个模拟器都有默认的端口号。mumu12默认16384。多开会导致分配不同的端口，要另行查看。开启hyper-v会导致端口不断变动，这块详细可参考MAA的[QA](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v)
> 3. 输入要执行的任务，用空格来间隔

MAABH3这边不需要手动填写adb路径和模拟器adb地址，会自动扫描的

**Comment by dongwlin** [comment]
> > 晚点会考虑，现在你是哪里不会用？
> 
> 能不能教教怎么读会更快入手？看得一头雾水，太久没接触编程和CPP，同时也比较菜。MaaFramwork那边又只有一个pipeline doc。想参与开发和弄一个无期迷途的但不会orz
> 
> 目前是下了个vs2022加断点main.cpp慢慢去看orz，有点难度。是不是从commit record那边从init开始慢慢看上去会比较好入手？

看framework的sample或者直接看MAABH3这边的cli就行了

**Comment by dongwlin** [comment]
> > 晚点会考虑，现在你是哪里不会用？
> 
> 能不能教教怎么读会更快入手？看得一头雾水，太久没接触编程和CPP，同时也比较菜。MaaFramwork那边又只有一个pipeline doc。想参与开发和弄一个无期迷途的但不会orz
> 
> 目前是下了个vs2022加断点main.cpp慢慢去看orz，有点难度。是不是从commit record那边从init开始慢慢看上去会比较好入手？

或者你也可以看看这个[MaaFrameworkCommonApp](https://github.com/dongwlin/MaaFrameworkCommonApp)，这个是MAABH3这边的cli的简化版本

**Comment by dongwlin** [comment]
README.md中已更新相关文字教程
