### ISSUE TITLE
舰团项操作失败（卡在舰团贡献页）

### ISSUE THREAD

**Issue by Rabbit-inmyheart** [MaaAssistantArknights/MAABH3#8]
进入舰团页面 -> 点击舰团贡献 -> 卡住
1. 卡住页面截图（MuMu模拟器12自带截图）：
[图片文件下载](https://www.aliyundrive.com/s/NL6Xg1tcgb6)
2. 完整log文件（由于模拟器同时运行了崩铁和崩三的脚本，可能存在一些与bug无关错误）：
[log文件下载](https://www.aliyundrive.com/s/rfyz2PimcN5)

**Comment by dongwlin** [comment]
修过了，等等发版
