### ISSUE TITLE
家园升级页面弹出会卡住不动

### ISSUE THREAD

**Issue by Rabbit-inmyheart** [MaaAssistantArknights/MAABH3#9]
![MuMu12-20231007-193015](https://github.com/MaaAssistantArknights/MAABH3/assets/62099472/9709c888-cf40-4e49-8b90-d6b45e05f424)

**Comment by dongwlin** [comment]
[v0.3.5](https://github.com/MaaAssistantArknights/MAABH3/releases/tag/v0.3.5) fixed
